### ISSUE TITLE
Java Incompatibility on Ubuntu 18.04

### ISSUE THREAD

**Issue by bclermont** [ZencashOfficial/zencash-swing-wallet-ui#126]
A few days ago, Ubuntu upgraded Java to 11 (somekind of weird 10.x+ patches it seem)

anyway, since then the wallet fail to show a full UI, only a 1x10 pixel windows and the following errors:

```
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2143)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1096)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:440)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1560)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:628)
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1403)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1516)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1482)
	at java.desktop/javax.swing.UIManager.getInstalledLookAndFeels(UIManager.java:422)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:603)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 23 more
java.lang.Error: no ComponentUI class for: javax.swing.JOptionPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,icon=,initialValue=,message="A general unexpected critical/unrecoverable error has occurred: 
  Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper 
 See the console/logfile output for more detailed error information!,messageType=ERROR_MESSAGE,optionType=DEFAULT_OPTION,wantsInput=false]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JOptionPane.updateUI(JOptionPane.java:1873)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1838)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:862)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:708)
```

To fix this, please update `debian/control` to depends on `openjdk-8-jre` instead of `default-jre` and call this one instead of `/usr/bin/java` in startup script.

for users who experience same problem as me, here are 2 solutions:

run as root:

```
apt-get install openjdk-8-jre
update-java-alternatives -s java-1.8.0-openjdk-amd64
```

or edit `/etc/java-11-openjdk/accessibility.properties` and comment `assistive_technologies=org.GNOME.Accessibility.AtkWrapper`

**Comment by tarrenj** [comment]
ACK, will attempt to reproduce issue and test fix.  @bclermont, would you like to submit a Pull Request for this so you get credit, or would you rather I take care of it?

**Comment by bclermont** [comment]
no need to take credits

**Comment by tarrenj** [comment]
ACK, I'll submit the PR after testing, <24 hours.

**Comment by tarrenj** [comment]
I've reproduced the issue, and confirmed that both of the given fixes work.

I misread the OP and thought you proposed a fix in the code, hence the PR suggestion.  I'll leave this issue open and assign it to our Swing developer.  Thanks for the great issue report!
