### ISSUE TITLE
Wallet export to arizen NoSuchElementException (master)

### ISSUE THREAD

**Issue by aballaci** [ZencashOfficial/zencash-swing-wallet-ui#86]
![zencash-wallet-0 80 2 4_arizen_export_error](https://user-images.githubusercontent.com/4948629/38466916-f1790e0e-3b30-11e8-9e0d-359658fb93e6.png)
SwingWorker-pool-2-thread-1] [Sun Apr 08 13:26:40 CEST 2018] [ERROR] Unexpected error:  
java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at com.vaklinov.zcashui.arizen.repo.ArizenWallet.insertAddressBatch(ArizenWallet.java:77)
	at com.vaklinov.zcashui.WalletOperations$1.doInBackground(WalletOperations.java:530)
	at com.vaklinov.zcashui.WalletOperations$1.doInBackground(WalletOperations.java:485)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vaklinov** [comment]
This seems to happen only when the wallet has no Z addresses created. Will be fixed.

**Comment by vaklinov** [comment]
The latest Git/master branch has a fix for this.
